[package]
name = "HTTP-Based-KV-Server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
dotenvy = "0.15.7"
sea-orm = { version = "2.0.0-rc", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
